#!/usr/bin/perl

my $self = shift;
open( my $app, '>', 'dategrep-standalone' )
  or die "Can't open dategrep-standalone: $!\n";
print $app <<'HEADER';
#!/usr/bin/env perl
# script autogenerated, do not patch

exit App::dategrep->run();

HEADER

open( my $lib, '<', 'lib/App/dategrep.pm' )
  or die "Can't open lib: $!\n";
while (<$lib>) {
    next if /^=pod/ .. /^=cut/;
    print {$app} $_;
}

open( my $pod, '<', 'bin/dategrep' )
  or die "Can't open pod: $!\n";
while (<$pod>) {
    if ( /^=pod/ .. /^=cut/ ) {
        print {$app} $_;
    }
}
