name="App-dategrep"
readme_from="script/dategrep"
abstract_from="script/dategrep"
license="gpl_3"
authors_from="script/dategrep"
badges = ['travis', 'coveralls' ]
tag_format="v%v"

[ReleaseTest]
MinimumVersion = false
