#!/bin/sh

set -e

version=$(perl -Ilib -MApp::dategrep -E 'say App::dategrep->VERSION')

{ cat <<EOF ; cat debian/changelog ; } > debian/changelog.$$ && mv debian/changelog.$$ debian/changelog 
dategrep ($version) unstable; urgency=low

  * Update to $version

 -- Mario Domgoergen <mario@domgoergen.com>  $(date -R)

EOF

exit 0
